### ISSUE TITLE
Appimage uses X11 on Wayland, no surface information on wayland.

### ISSUE THREAD

**Issue by codecnotsupported** [SaschaWillems/VulkanCapsViewer#140] opened 2022-03-02 19:44 UTC
- Appimage uses X11.
- No surface information.
![image](https://user-images.githubusercontent.com/2294209/156437340-00dda514-65d0-4eda-8277-d26e485e300f.png)

**Comment by SaschaWillems** [comment] 2022-05-06 16:20
Sorry, I don't have a platform to test this on. Can you elaborate? Can you run the app with the "log" argument and attach the log file?

**Comment by codecnotsupported** [comment] 2022-05-07 11:36
[Waiting for this issue to be resolved first.](https://github.com/SaschaWillems/VulkanCapsViewer/issues/142)

**Comment by QuartzIsCheap** [comment] 2022-05-25 15:01
Hello,
I've decided to give Wayland a go with Ubuntu, and faced the same issue.
![image](https://user-images.githubusercontent.com/25138310/170290730-abd9ef38-da00-421e-9b9c-9919ae6c76d9.png)

Here is the log file.
[log.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/8772163/log.txt)

The first line written to the terminal when launching the application (with --log, it does not appear in the file) is this :
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
I'm guessing that's the cause of the issue.

I am available for further information/testing.

**Comment by SaschaWillems** [comment] 2022-05-26 14:15
I'd need someone with a wayland setup and some experience to do a PR to fix this.

**Comment by loonycyborg** [comment] 2022-07-28 19:03
Shouldn't pr #109 fix this? It does make surface information appear for me while it doesn't appear otherwise. I'm on GNOME/Wayland using AMD RADV POLARIS12 gpu.

**Comment by SaschaWillems** [comment] 2022-12-26 08:35
Can you check again with the latest version? #155 did a fix to the Wayland build that may have fixed this.

**Comment by RunningDroid** [comment] 2022-12-30 18:51
I tested with a binary built from git (c8ff23e) and it doesn't rely on XWayland anymore*, but there's still no surface information:
![2022-12-30T12:58:15,068252944-05:00](https://user-images.githubusercontent.com/486393/210099839-6882c976-5203-4d0d-8693-d2d84bcc9aab.png)
[log.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/10325782/log.txt)

I don't know if I resolved the conflicts right when I rebased it but I tested #109 as well and it didn't show the surface information either.

*:I have sway configured to tell me if an application is relying on XWayland:
![2022-12-30T13:10:15,830116657-05:00](https://user-images.githubusercontent.com/486393/210100340-3611b894-b3fa-42b5-894b-305efc533f2a.png)

**Comment by SaschaWillems** [comment] 2023-05-29 16:31
Can you check if this is fixed in the latest version?

**Comment by codecnotsupported** [comment] 2023-05-29 18:18
On Kubuntu 23.04: Nvidia PPA for latest drivers:
`./vulkancapsviewer_3.31_linux64_wayland.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libVkLayer_MESA_device_select.so: undefined symbol: wl_proxy_marshal_flags`
Workaround: `sudo apt remove mesa-vulkan-drivers:amd64`
Works fine otherwise.
![Screenshot_20230529_200207](https://github.com/SaschaWillems/VulkanCapsViewer/assets/2294209/65d4b3a7-88eb-4bf8-b2a7-8c17fea62a8e)

On Kubuntu 23.04: AMD (Integrated) Mesa:  (Tried both bleeding edge & stable)
`./vulkancapsviewer_3.31_linux64_wayland.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libVkLayer_MESA_device_select.so: undefined symbol: wl_proxy_marshal_flags`

**Comment by codecnotsupported** [comment] 2023-05-29 18:31
I extracted the appimage and ran ldd on the binary. 
`libwayland-client.so.0 => /home/acewing/Downloads/squashfs-root/usr/bin/./../lib/libwayland-client.so.0 (0x00007f3962e8d000)`
It seems libwayland is still statically linked.
Running `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 ./vulkanCapsViewer`
Fixes the problem.
![image](https://github.com/SaschaWillems/VulkanCapsViewer/assets/2294209/fb98e05d-d9f4-4014-8c58-09ae7255374d)
Pull: https://github.com/SaschaWillems/VulkanCapsViewer/commit/0b11364efeb68da06c1d889833d1a7e50aadbfa6
doesn't exclude the `libwayland-client.so.0` but it is the solution to this problem.

**Comment by codecnotsupported** [comment] 2023-05-29 18:31
I extracted the appimage and ran ldd on the binary. 
`libwayland-client.so.0 => /home/user/Downloads/squashfs-root/usr/bin/./../lib/libwayland-client.so.0 (0x00007f3962e8d000)`
It seems libwayland is still statically linked.
Running `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 ./vulkanCapsViewer`
Fixes the problem.
![image](https://github.com/SaschaWillems/VulkanCapsViewer/assets/2294209/fb98e05d-d9f4-4014-8c58-09ae7255374d)
Pull: https://github.com/SaschaWillems/VulkanCapsViewer/commit/0b11364efeb68da06c1d889833d1a7e50aadbfa6
doesn't exclude the `libwayland-client.so.0` but it is the solution to this problem.

**Comment by codecnotsupported** [comment] 2023-05-29 18:35
https://github.com/SaschaWillems/VulkanCapsViewer/commit/0b11364efeb68da06c1d889833d1a7e50aadbfa6#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R81
```
./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage -exclude-libs=libwayland-client.so
```
Maybe change it from:
`-appimage -exclude-libs=libwayland-client.so `
to
`-appimage -exclude-libs=libwayland-client.so.0`

**Comment by SaschaWillems** [comment] 2023-05-29 18:43
Thx for testing. Can you comment this here: https://github.com/SaschaWillems/VulkanCapsViewer/pull/171

I don't have a setup to test this, so any PR is welcome.

**Comment by codecnotsupported** [comment] 2023-05-29 18:55
Ok, done. You want me to create a pull request or have [firescry](https://github.com/firescry) amend his pull request? (If that's possible.)

**Comment by codecnotsupported** [comment] 2023-05-29 19:05
#179 have it either way.

**Comment by SopaDeMacaco-UmaDelicia** [comment] 2023-09-04 01:20
> Workaround: `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 ./vulkanCapsViewer`

Still doesn't run the app in wayland mode, it works via xwayland.

**Comment by firescry** [comment] 2023-09-10 14:54
Change from #171 is available in release `3.32`. Official Wayland binary from https://vulkan.gpuinfo.org/download.php works for me, so please check if it solves the problem for you too :)

**Comment by RunningDroid** [comment] 2023-09-11 05:57
It seems like Github decided not to notify me until @firescry  commented here.

The latest release appears to change where the error is for me, if I run `QT_QPA_PLATFORM=wayland-egl ./vulkancapsviewer_3.32_linux64_wayland.AppImage` (telling QT to only use wayland,) I get this on stdout:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

zsh: IOT instruction (core dumped)  ./vulkancapsviewer_3.32_linux64_wayland.AppImage
```
(because the appimage doesn't have the qt5-wayland plugin and it doesn't want to load my system's copy for some reason, I don't know enough about AppImages or QT to know)

if I unset  QT_QPA_PLATFORM I get some logs then a segfault:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Reading extensions
Device "AMD Radeon Graphics"
Reading Vulkan 1.1 core properties
Reading Vulkan 1.2 core properties
Reading Vulkan 1.3 core properties
Reading layers
Reading queue families
Reading physical feattures
Reading Vulkan 1.1 core features
Reading Vulkan 1.2 core features
Reading Vulkan 1.3 core features
Reading limits
Reading memory properties
Reading surface info
zsh: segmentation fault (core dumped)  ./vulkancapsviewer_3.32_linux64_wayland.AppImage
```
[xcb-only.bt.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/12572362/xcb-only.bt.txt)
(the logs and backtrace are the same if I LD_PRELOAD my system's libwayland-client.so)

And I was able to get slightly more detail in the backtrace with a local build after I cloned wayland's source and checked out the release I built against (1.22.0): [local-build.bt.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/12572543/local-build.bt.txt)
This part looks important ([link to the source file](https://gitlab.freedesktop.org/wayland/wayland/-/blob/1.22.0/src/wayland-client.c?ref_type=tags#L2446)), but I don't know enough C to know if it's the source of the segfault:
``` backtrace
Thread 1 "vulkanCapsViewe" received signal SIGSEGV, Segmentation fault.
wl_proxy_create_wrapper (proxy=0x0) at ../src/wayland-client.c:2446
warning: Source file is more recent than executable.
2446		pthread_mutex_lock(&wrapped_proxy->display->mutex);
```

Also, I suspect the reason I had it running when I wrote my previous comment was because I wasn't telling qmake to enable the wayland bits.

**Comment by SaschaWillems** [comment] 2023-10-28 16:48
Closing due to inactivity. If the issue still persists, feel free to open a new issue.

**Closed by SaschaWillems** 2023-10-28 16:48 UTC
Labels: Platform: Linux
