### ISSUE TITLE
Regarding "fake" database entries for Fermi based GPUs

### ISSUE THREAD

**Issue by Gwani** [SaschaWillems/VulkanCapsViewer#4] opened 2016-02-18 08:16 UTC
Hi there!

i just wanted to document how the Caps Viewer behaves when having a mobile Fermi GTX560M installed in conjuction with NVidias Vulkan-supporting Beta driver for Windows (356.39) and LunarG's Vulkan SDK. The Version of the Caps Viewer is an unmodified version (Beta 1.0 (64-Bit) (2016-02-16, API-Version 1.0.3)) I downloaded from vulkan.gpuinfo.org:

Starting the Viewer gives me:
![1](https://cloud.githubusercontent.com/assets/3669173/13137166/7bc8e21a-d61f-11e5-9181-fb4e72127465.png)
But then, after klicking OK, it gives me:
![2](https://cloud.githubusercontent.com/assets/3669173/13137174/8ea90d7e-d61f-11e5-89b5-dc4d9baf4820.png)
and
![3](https://cloud.githubusercontent.com/assets/3669173/13137195/aad54b70-d61f-11e5-9291-05b59c3bab32.png)
Formats are empty and Layers show the LunarG stuff.
I don't know what happens when I press "Upload", but my guess is that it will probably push the data I'm seeing there and thus might be the cause of the "fake" entries.

Cheers,
Gwani

**Comment by SaschaWillems** [comment] 2016-02-18 08:19
Thank you very much for this detailled information. This is a bug in the current version and will be fixed in a future version.

As a temporary workaround I have disabled upload of reports without formats on the server side and will remove the invalid reports.

**Comment by timjp87** [comment] 2016-02-18 12:50
Why does it manage to execute this part, though:
https://github.com/SaschaWillems/VulkanCapsViewer/blob/d5c5f3fb9c2e1205744802ebe0ba4f89eb22d21e/vulkanDeviceInfo.hpp#L199-L206
For me that looks like it actually entered the driver and fetched all the information to populate the pointer to props so that the deviceid can be printed out. I am using a GTX 580 and if it doesn't have a Vulkan driver, why does it return a deviceid that must be somehow in the Vulkan driver and is associated with the 580 model?

**Comment by SaschaWillems** [comment] 2016-02-18 13:06
This is a beta driver and may be an unintentional left over. There is (currently) no Vulkan support for Fermi (NV confirmed this).

And since not a single format is supported, it's no usable Vulkan implementation.

**Comment by SaschaWillems** [comment] 2016-03-04 20:08
Closing this as recent drivers won't expose Vulkan on non-supported GPUs anymore. I also deleted the  fermi reports from the database.

**Closed by SaschaWillems** 2016-03-04 20:08 UTC
