### ISSUE TITLE
gpuinfo.org not correctly reporting subgroup supported operations

### ISSUE THREAD

**Issue by allanmac** [SaschaWillems/VulkanCapsViewer#54] opened 2018-10-28 18:57 UTC
Example [here](http://vulkan.gpuinfo.org/displayreport.php?id=4407#device).

The `supportedOperations` mask is 189 (10111101).

The Viewer (1.9) correctly reports that `vote` and `clustered` are not supported.

The gpuinfo.org report indicates `vote` is supported despite the mask being 189.

**Comment by SaschaWillems** [comment] 2018-10-29 07:17
Thanks for noticing. This was caused by a wrong value in the back-end function of the web-site and should be fixed now.

**Closed by SaschaWillems** 2018-10-29 07:17 UTC
